services:
  - type: web
    name: employee-management-jwt-mini-project
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    healthCheckPath: /health
